substitutions:
  _GCS_CACHE_BUCKET: cloudbuild-m2repo

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'env'
    entrypoint: 'bash'
    args:
      - -c
      - |

        if [[ -z "$_NAMESPACE" ]]; then
          NAMESPACE=$$(scripts/extract-namespace.sh branche $BRANCH_NAME)
        else
          NAMESPACE=$_NAMESPACE
        fi

        VERSION=$$(scripts/extract-version.sh branche $BRANCH_NAME)
        IMAGE_NAME=eu.gcr.io/${PROJECT_ID}/ked-pdi
        IS_IMAGE_EXIST=$$(scripts/image-exists.sh $$IMAGE_NAME $SHORT_SHA)

        echo "Branch: $BRANCH_NAME"
        echo "Commit: $SHORT_SHA"
        echo "Env: $$NAMESPACE"
        echo "Version: $$VERSION"
        echo "Image: $$IMAGE_NAME"
        echo "Is image exists ? $$IS_IMAGE_EXIST"

        echo "export TAG_ENV=$$NAMESPACE" > /workspace/build.env
        echo "export TAG_VERSION=$$VERSION" >> /workspace/build.env
        echo "export IMAGE_NAME=$$IMAGE_NAME" >> /workspace/build.env
        echo "export IS_IMAGE_EXIST=$$IS_IMAGE_EXIST" >> /workspace/build.env

  #build
  - name: gcr.io/cloud-builders/gcloud
    id: 'build'
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/build.env
        gcloud builds submit \
              --config=cloudbuild/cloudbuild-build-pipeline.yaml \
              --substitutions=_ENV=$$TAG_ENV,_VERSION=$$TAG_ENV


  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          gcloud builds submit \
                --config=cloudbuild/cloudbuild-deploy-pipeline.yaml \
                --substitutions=_ENV=$$TAG_ENV,_VERSION=$$TAG_ENV


timeout: 9000s
tags: ['push']
options:
  substitution_option: 'ALLOW_LOOSE'
