substitutions:
  _IMAGE_NAME: eu.gcr.io/${PROJECT_ID}/ked-pdi
  _IMAGE_TAG: ${_VERSION}
  _SERVICE_NAME: ${_ENV}-ked-pdi

steps:
  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy-to-cloud-run'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          gcloud beta run deploy ${_SERVICE_NAME} \
            --image=${_IMAGE_NAME}:${_IMAGE_TAG} \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=512M \
            --min-instances=1 \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID},ENV=${_ENV},VERSION=${_VERSION},IMAGE_TAG=${_IMAGE_TAG} \
            --update-labels=env=${_ENV},version=${_VERSION},image_tag=${_IMAGE_TAG}

timeout: 9000s
tags: ['deploy','${_SHORT_SHA}','${_VERSION}','${_ENV}']

options:
  dynamic_substitutions: true
