substitutions:
  _IMAGE_NAME: eu.gcr.io/${PROJECT_ID}/ked-pdi

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'config-env'
    entrypoint: 'bash'
    args:
      - -c
      - |
        scripts/config-env.sh tag $TAG_NAME $_IMAGE_NAME $SHORT_SHA > /workspace/build.env
        source /workspace/build.env
        printenv ENV VERSION IMAGE_NAME IS_IMAGE_EXIST

  - name: gcr.io/cloud-builders/docker
    id: 'pull-tag-and-push-image'
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/build.env
        if [[ "$$IS_IMAGE_EXIST" == true ]]
        then
            docker pull ${_IMAGE_NAME}:${SHORT_SHA}

            docker tag ${_IMAGE_NAME}:${SHORT_SHA} \
                       ${_IMAGE_NAME}:$${ENV}
            docker tag ${_IMAGE_NAME}:${SHORT_SHA} \
                       ${_IMAGE_NAME}:$${VERSION}

            docker push ${_IMAGE_NAME}:$${ENV}
            docker push ${_IMAGE_NAME}:$${VERSION}
        else
            echo "Image $SHORT_SHA not exists !"
        fi
  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'git-push-branch'
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/build.env
        if [[ "$$IS_IMAGE_EXIST" == true && "$$VERSION" =~ ^[0-9]\.[0-9]\.X-rc$ ]]
        then
            gcloud builds submit \
                --config=cloudbuild/cloudbuild-branch-pipeline.yaml \
                --substitutions=_ENV=$$ENV,_VERSION=$$VERSION,_SHORT_SHA=$SHORT_SHA,_REPO_NAME=$REPO_NAME
        else
            echo "Image $SHORT_SHA not exists !"
        fi

  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          if [[ "$$IS_IMAGE_EXIST" == true ]]
          then
              gcloud builds submit \
                  --config=cloudbuild/cloudbuild-deploy-pipeline.yaml \
                  --substitutions=_ENV=$$ENV,_VERSION=$$VERSION,_IMAGE_TAG=$SHORT_SHA,_IMAGE_NAME=$_IMAGE_NAME,_SERVICE_NAME=$${ENV}-ked-pdi,_SHORT_SHA=$SHORT_SHA
          else
              echo "Image $SHORT_SHA not exists !"
          fi

timeout: 9000s
tags: ['tag','${SHORT_SHA}']
options:
  substitution_option: 'ALLOW_LOOSE'
