substitutions:
  _GCS_CACHE_BUCKET: cloudbuild-m2repo

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'env'
    entrypoint: 'bash'
    args:
      - -c
      - |

        IMAGE_NAME=eu.gcr.io/${PROJECT_ID}/ked-pdi

        ./scripts/config-env.sh branch $$BRANCH_NAME $$IMAGE_NAME $SHORT_SHA > /workspace/build.env

        ls -la .

        source /workspace/build.env

        echo "Branch: $BRANCH_NAME"
        echo "Commit: $SHORT_SHA"
        echo "Env: $$ENV"
        echo "Version: $$VERSION"
        echo "Image: $$IMAGE_NAME"
        echo "Is image exists ? $$IS_IMAGE_EXIST"

        exit 1

  #build
  - name: gcr.io/cloud-builders/gcloud
    id: 'build'
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/build.env
        gcloud builds submit \
              --config=cloudbuild/cloudbuild-build-pipeline.yaml \
              --substitutions=_ENV=$$ENV,_VERSION=$$VERSION,_SHORT_SHA=$SHORT_SHA,_IMAGE_NAME=$$IMAGE_NAME


  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          gcloud builds submit \
                --config=cloudbuild/cloudbuild-deploy-pipeline.yaml \
                --substitutions=_ENV=$$ENV,_VERSION=$$VERSION,_SHORT_SHA=$SHORT_SHA,_IMAGE_NAME=$$IMAGE_NAME


timeout: 9000s
tags: ['push']
options:
  substitution_option: 'ALLOW_LOOSE'
