substitutions:
  _IMAGE_NAME: eu.gcr.io/${PROJECT_ID}/ked-pdi

steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'config-env'
    entrypoint: 'bash'
    args:
      - -c
      - |
        scripts/config-env.sh tag $TAG_NAME $_IMAGE_NAME $SHORT_SHA > /workspace/build.env
        source /workspace/build.env
        printenv ENV VERSION IMAGE_NAME IS_IMAGE_EXIST

  - name: gcr.io/cloud-builders/docker
    id: 'pull-tag-and-push-image'
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/build.env

        docker pull ${_IMAGE_NAME}:${_SHORT_SHA}

        docker tag ${_IMAGE_NAME}:${_SHORT_SHA} \
                   ${_IMAGE_NAME}:${_ENV}
        docker tag ${_IMAGE_NAME}:${_SHORT_SHA} \
                   ${_IMAGE_NAME}:${_VERSION}

        docker push ${_IMAGE_NAME}:${_ENV}
        docker push ${_IMAGE_NAME}:${_VERSION}

  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          if [[ "$$IS_IMAGE_EXIST" == false ]]
          then
              gcloud builds submit \
                  --config=cloudbuild/cloudbuild-deploy-pipeline.yaml \
                  --substitutions=_ENV=$$ENV,_VERSION=$$VERSION,_SHORT_SHA=$SHORT_SHA,_IMAGE_NAME=$_IMAGE_NAME,_SERVICE_NAME=$${ENV}-ked-pdi
          else
              echo "Image $SHORT_SHA exists !"
          fi

timeout: 9000s
tags: ['push']
options:
  substitution_option: 'ALLOW_LOOSE'
