
steps:
  #deploy
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy'
    entrypoint: bash
    args:
        - -c
        - |
          source /workspace/build.env
          gcloud run deploy ${_ENV}-ked-pdi \
            --image=${_IMAGE_NAME}:${_SHORT_SHA} \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=512M \
            --set-env-vars=GOOGLE_CLOUD_PROJECT=${PROJECT_ID},ENV=${_ENV},VERSION=${_VERSION},SHORT_SHA=${_SHORT_SHA}

timeout: 9000s
tags: ['deploy','${_ENV}','${_VERSION}','${_SHORT_SHA}']

