# Actuator configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
      exposure:
        include: "info,health,prometheus"
      path-mapping:
        prometheus: metrics
  # Actuator endpoints
  endpoint:
    prometheus:
      enabled: false
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  info:
    git:
      mode: full
info:
  project: ${GOOGLE_CLOUD_PROJECT}
  env: ${ENV}
  version: ${VERSION}
  image-tag: ${IMAGE_TAG}


